const fs = require('fs');
const path = require('path');

const appDir = path.join('c:', 'Users', 'DEVESH', 'Downloads', 'smart-finance', 'app', 'src', 'app');

// Ensure dirs
fs.mkdirSync(path.join(appDir, '(auth)'), { recursive: true });
fs.mkdirSync(path.join(appDir, '(tabs)'), { recursive: true });

const files = {
  '_layout.tsx': import { Stack } from 'expo-router';\n\nexport default function RootLayout() {\n  return (\n    <Stack screenOptions={{ headerShown: false }}>\n      <Stack.Screen name="(auth)" />\n      <Stack.Screen name="(tabs)" />\n      <Stack.Screen name="ai-assistant" options={{ presentation: 'modal' }} />\n    </Stack>\n  );\n},
  'index.tsx': import { Redirect } from 'expo-router';\nexport default function Index() {\n  return <Redirect href="/(auth)/login" />;\n},
  '(auth)/login.tsx': import React from 'react';\nimport { View, Text, TextInput, TouchableOpacity, StyleSheet } from 'react-native';\nimport { useRouter } from 'expo-router';\n\nexport default function Login() {\n  const router = useRouter();\n  return (\n    <View style={styles.container}>\n      <Text style={styles.title}>Smart Finance</Text>\n      <Text style={styles.subtitle}>Login to your premium account</Text>\n      <TextInput style={styles.input} placeholder="Email" placeholderTextColor="#aaa" />\n      <TextInput style={styles.input} placeholder="Password" secureTextEntry placeholderTextColor="#aaa" />\n      <TouchableOpacity style={styles.btn} onPress={() => router.replace('/(tabs)')}>\n        <Text style={styles.btnText}>Login</Text>\n      </TouchableOpacity>\n      <TouchableOpacity onPress={() => router.push('/(auth)/register')}>\n        <Text style={styles.link}>New user? Register here</Text>\n      </TouchableOpacity>\n    </View>\n  );\n}\nconst styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#121212', justifyContent: 'center', padding: 20 }, title: { color: '#fff', fontSize: 32, fontWeight: 'bold', marginBottom: 10 }, subtitle: { color: '#888', marginBottom: 30 }, input: { backgroundColor: '#1e1e1e', color: '#fff', padding: 15, borderRadius: 10, marginBottom: 15 }, btn: { backgroundColor: '#BB86FC', padding: 15, borderRadius: 10, alignItems: 'center' }, btnText: { fontWeight: 'bold', fontSize: 16 }, link: { color: '#BB86FC', marginTop: 20, textAlign: 'center' } });,
  '(auth)/register.tsx': import React from 'react';\nimport { View, Text, TextInput, TouchableOpacity, StyleSheet } from 'react-native';\nimport { useRouter } from 'expo-router';\n\nexport default function Register() {\n  const router = useRouter();\n  return (\n    <View style={styles.container}>\n      <Text style={styles.title}>Create Account</Text>\n      <TextInput style={styles.input} placeholder="Full Name" placeholderTextColor="#aaa" />\n      <TextInput style={styles.input} placeholder="Email" placeholderTextColor="#aaa" />\n      <TextInput style={styles.input} placeholder="Password" secureTextEntry placeholderTextColor="#aaa" />\n      <TouchableOpacity style={styles.btn} onPress={() => router.replace('/(tabs)')}>\n        <Text style={styles.btnText}>Register</Text>\n      </TouchableOpacity>\n      <TouchableOpacity onPress={() => router.back()}>\n        <Text style={styles.link}>Already have an account? Login</Text>\n      </TouchableOpacity>\n    </View>\n  );\n}\nconst styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#121212', justifyContent: 'center', padding: 20 }, title: { color: '#fff', fontSize: 32, fontWeight: 'bold', marginBottom: 30 }, input: { backgroundColor: '#1e1e1e', color: '#fff', padding: 15, borderRadius: 10, marginBottom: 15 }, btn: { backgroundColor: '#03DAC6', padding: 15, borderRadius: 10, alignItems: 'center' }, btnText: { fontWeight: 'bold', fontSize: 16 }, link: { color: '#03DAC6', marginTop: 20, textAlign: 'center' } });,
  '(tabs)/_layout.tsx': import { Tabs } from 'expo-router';\n\nexport default function TabLayout() {\n  return (\n    <Tabs screenOptions={{ headerShown: false, tabBarStyle: { backgroundColor: '#1e1e1e', borderTopWidth: 0 }, tabBarActiveTintColor: '#BB86FC', tabBarInactiveTintColor: '#888' }}>\n      <Tabs.Screen name="index" options={{ title: 'Home' }} />\n      <Tabs.Screen name="expenses" options={{ title: 'Expenses' }} />\n      <Tabs.Screen name="emi" options={{ title: 'EMI' }} />\n      <Tabs.Screen name="savings" options={{ title: 'Savings' }} />\n      <Tabs.Screen name="profile" options={{ title: 'Profile' }} />\n    </Tabs>\n  );\n},
  '(tabs)/index.tsx': import React from 'react';\nimport { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';\nimport { useRouter } from 'expo-router';\n\nexport default function Dashboard() {\n  const router = useRouter();\n  return (\n    <ScrollView style={styles.container}>\n      <View style={styles.header}><Text style={styles.title}>Dashboard</Text></View>\n      <View style={styles.card}>\n        <Text style={styles.cardTitle}>Total Balance</Text>\n        <Text style={styles.amount}>₹ 1,24,500</Text>\n      </View>\n      <TouchableOpacity style={styles.aiBtn} onPress={() => router.push('/ai-assistant')}>\n        <Text style={styles.aiText}>🤖 Ask AI Assistant</Text>\n      </TouchableOpacity>\n    </ScrollView>\n  );\n}\nconst styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#121212' }, header: { padding: 20, paddingTop: 60 }, title: { color: '#fff', fontSize: 28, fontWeight: 'bold' }, card: { backgroundColor: '#1e1e1e', margin: 20, padding: 20, borderRadius: 15 }, cardTitle: { color: '#888', fontSize: 16 }, amount: { color: '#BB86FC', fontSize: 32, fontWeight: 'bold', marginTop: 10 }, aiBtn: { backgroundColor: '#03DAC6', margin: 20, padding: 15, borderRadius: 10, alignItems: 'center' }, aiText: { fontWeight: 'bold', fontSize: 16 } });,
  '(tabs)/expenses.tsx': import React from 'react';\nimport { View, Text, StyleSheet } from 'react-native';\nexport default function Expenses() { return <View style={styles.container}><Text style={styles.title}>Expense Manager</Text></View>; }\nconst styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#121212', justifyContent: 'center', alignItems: 'center' }, title: { color: '#fff', fontSize: 24 } });,
  '(tabs)/emi.tsx': import React from 'react';\nimport { View, Text, StyleSheet } from 'react-native';\nexport default function EMI() { return <View style={styles.container}><Text style={styles.title}>EMI Manager</Text></View>; }\nconst styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#121212', justifyContent: 'center', alignItems: 'center' }, title: { color: '#fff', fontSize: 24 } });,
  '(tabs)/savings.tsx': import React from 'react';\nimport { View, Text, StyleSheet } from 'react-native';\nexport default function Savings() { return <View style={styles.container}><Text style={styles.title}>Savings Planner</Text></View>; }\nconst styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#121212', justifyContent: 'center', alignItems: 'center' }, title: { color: '#fff', fontSize: 24 } });,
  '(tabs)/profile.tsx': import React from 'react';\nimport { View, Text, StyleSheet } from 'react-native';\nexport default function Profile() { return <View style={styles.container}><Text style={styles.title}>Profile & Settings</Text></View>; }\nconst styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#121212', justifyContent: 'center', alignItems: 'center' }, title: { color: '#fff', fontSize: 24 } });,
  'ai-assistant.tsx': import React from 'react';\nimport { View, Text, StyleSheet } from 'react-native';\nexport default function AIAssistant() { return <View style={styles.container}><Text style={styles.title}>AI Chat</Text></View>; }\nconst styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#121212', justifyContent: 'center', alignItems: 'center' }, title: { color: '#fff', fontSize: 24 } });
};

for (const [name, content] of Object.entries(files)) {
  fs.writeFileSync(path.join(appDir, name), content);
}
console.log('Frontend flow generated successfully');
